### PR TITLE
Migrate from Zend to Laminas

### LINKED ISSUE #243: Drop support for zendframework components and require Laminas instead

### PR DESCRIPTION
**Pull request by MadCat34**
Closes #243 :-)

### CODE REVIEW

**Comment by acelaya** [comment]
Amazing!

I will take a deeper look tomorrow.

**Comment by MadCat34** [comment]
I have used  https://github.com/laminas/laminas-migration :-)

**Comment by acelaya** [comment]
Hey @MadCat34.

I have seen that fro some reason, the CI build has not been triggered (I'm not sure why), so I have cloned your branch and run the build locally to make sure nothing was broken.

I have fixed the build, together with some typos, but I don't seem to have permissions to push to your branch. Could you kindly enable it? There should be a checkbox in the right side-bar saying "Allow edits from maintainers".

**Comment by MadCat34** [comment]
Hi @acelaya ,
Ok, I have enabled it :-)

**Comment by acelaya** [comment]
Thanks a lot for the contribution @MadCat34 :smiley:

**Comment by MadCat34** [comment]
Glad to have helped you

**Pull request merged**
